// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ArticleMeta is the predicate function for articlemeta builders.
type ArticleMeta func(*sql.Selector)
