// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"mikanani-v2/internal/data/ent/animemeta"
	"mikanani-v2/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AnimeMetaDelete is the builder for deleting a AnimeMeta entity.
type AnimeMetaDelete struct {
	config
	hooks    []Hook
	mutation *AnimeMetaMutation
}

// Where appends a list predicates to the AnimeMetaDelete builder.
func (amd *AnimeMetaDelete) Where(ps ...predicate.AnimeMeta) *AnimeMetaDelete {
	amd.mutation.Where(ps...)
	return amd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (amd *AnimeMetaDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, amd.sqlExec, amd.mutation, amd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (amd *AnimeMetaDelete) ExecX(ctx context.Context) int {
	n, err := amd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (amd *AnimeMetaDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(animemeta.Table, sqlgraph.NewFieldSpec(animemeta.FieldID, field.TypeInt))
	if ps := amd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, amd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	amd.mutation.done = true
	return affected, err
}

// AnimeMetaDeleteOne is the builder for deleting a single AnimeMeta entity.
type AnimeMetaDeleteOne struct {
	amd *AnimeMetaDelete
}

// Where appends a list predicates to the AnimeMetaDelete builder.
func (amdo *AnimeMetaDeleteOne) Where(ps ...predicate.AnimeMeta) *AnimeMetaDeleteOne {
	amdo.amd.mutation.Where(ps...)
	return amdo
}

// Exec executes the deletion query.
func (amdo *AnimeMetaDeleteOne) Exec(ctx context.Context) error {
	n, err := amdo.amd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{animemeta.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (amdo *AnimeMetaDeleteOne) ExecX(ctx context.Context) {
	if err := amdo.Exec(ctx); err != nil {
		panic(err)
	}
}
