// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"
	"mikanani-v2/internal/data/ent/animemeta"
	"mikanani-v2/internal/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AnimeMetaQuery is the builder for querying AnimeMeta entities.
type AnimeMetaQuery struct {
	config
	ctx        *QueryContext
	order      []animemeta.OrderOption
	inters     []Interceptor
	predicates []predicate.AnimeMeta
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AnimeMetaQuery builder.
func (amq *AnimeMetaQuery) Where(ps ...predicate.AnimeMeta) *AnimeMetaQuery {
	amq.predicates = append(amq.predicates, ps...)
	return amq
}

// Limit the number of records to be returned by this query.
func (amq *AnimeMetaQuery) Limit(limit int) *AnimeMetaQuery {
	amq.ctx.Limit = &limit
	return amq
}

// Offset to start from.
func (amq *AnimeMetaQuery) Offset(offset int) *AnimeMetaQuery {
	amq.ctx.Offset = &offset
	return amq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (amq *AnimeMetaQuery) Unique(unique bool) *AnimeMetaQuery {
	amq.ctx.Unique = &unique
	return amq
}

// Order specifies how the records should be ordered.
func (amq *AnimeMetaQuery) Order(o ...animemeta.OrderOption) *AnimeMetaQuery {
	amq.order = append(amq.order, o...)
	return amq
}

// First returns the first AnimeMeta entity from the query.
// Returns a *NotFoundError when no AnimeMeta was found.
func (amq *AnimeMetaQuery) First(ctx context.Context) (*AnimeMeta, error) {
	nodes, err := amq.Limit(1).All(setContextOp(ctx, amq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{animemeta.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (amq *AnimeMetaQuery) FirstX(ctx context.Context) *AnimeMeta {
	node, err := amq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first AnimeMeta ID from the query.
// Returns a *NotFoundError when no AnimeMeta ID was found.
func (amq *AnimeMetaQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = amq.Limit(1).IDs(setContextOp(ctx, amq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{animemeta.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (amq *AnimeMetaQuery) FirstIDX(ctx context.Context) int {
	id, err := amq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single AnimeMeta entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one AnimeMeta entity is found.
// Returns a *NotFoundError when no AnimeMeta entities are found.
func (amq *AnimeMetaQuery) Only(ctx context.Context) (*AnimeMeta, error) {
	nodes, err := amq.Limit(2).All(setContextOp(ctx, amq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{animemeta.Label}
	default:
		return nil, &NotSingularError{animemeta.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (amq *AnimeMetaQuery) OnlyX(ctx context.Context) *AnimeMeta {
	node, err := amq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only AnimeMeta ID in the query.
// Returns a *NotSingularError when more than one AnimeMeta ID is found.
// Returns a *NotFoundError when no entities are found.
func (amq *AnimeMetaQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = amq.Limit(2).IDs(setContextOp(ctx, amq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{animemeta.Label}
	default:
		err = &NotSingularError{animemeta.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (amq *AnimeMetaQuery) OnlyIDX(ctx context.Context) int {
	id, err := amq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of AnimeMetaSlice.
func (amq *AnimeMetaQuery) All(ctx context.Context) ([]*AnimeMeta, error) {
	ctx = setContextOp(ctx, amq.ctx, "All")
	if err := amq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*AnimeMeta, *AnimeMetaQuery]()
	return withInterceptors[[]*AnimeMeta](ctx, amq, qr, amq.inters)
}

// AllX is like All, but panics if an error occurs.
func (amq *AnimeMetaQuery) AllX(ctx context.Context) []*AnimeMeta {
	nodes, err := amq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of AnimeMeta IDs.
func (amq *AnimeMetaQuery) IDs(ctx context.Context) (ids []int, err error) {
	if amq.ctx.Unique == nil && amq.path != nil {
		amq.Unique(true)
	}
	ctx = setContextOp(ctx, amq.ctx, "IDs")
	if err = amq.Select(animemeta.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (amq *AnimeMetaQuery) IDsX(ctx context.Context) []int {
	ids, err := amq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (amq *AnimeMetaQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, amq.ctx, "Count")
	if err := amq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, amq, querierCount[*AnimeMetaQuery](), amq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (amq *AnimeMetaQuery) CountX(ctx context.Context) int {
	count, err := amq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (amq *AnimeMetaQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, amq.ctx, "Exist")
	switch _, err := amq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (amq *AnimeMetaQuery) ExistX(ctx context.Context) bool {
	exist, err := amq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AnimeMetaQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (amq *AnimeMetaQuery) Clone() *AnimeMetaQuery {
	if amq == nil {
		return nil
	}
	return &AnimeMetaQuery{
		config:     amq.config,
		ctx:        amq.ctx.Clone(),
		order:      append([]animemeta.OrderOption{}, amq.order...),
		inters:     append([]Interceptor{}, amq.inters...),
		predicates: append([]predicate.AnimeMeta{}, amq.predicates...),
		// clone intermediate query.
		sql:  amq.sql.Clone(),
		path: amq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UID int64 `json:"uid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.AnimeMeta.Query().
//		GroupBy(animemeta.FieldUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (amq *AnimeMetaQuery) GroupBy(field string, fields ...string) *AnimeMetaGroupBy {
	amq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AnimeMetaGroupBy{build: amq}
	grbuild.flds = &amq.ctx.Fields
	grbuild.label = animemeta.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UID int64 `json:"uid,omitempty"`
//	}
//
//	client.AnimeMeta.Query().
//		Select(animemeta.FieldUID).
//		Scan(ctx, &v)
func (amq *AnimeMetaQuery) Select(fields ...string) *AnimeMetaSelect {
	amq.ctx.Fields = append(amq.ctx.Fields, fields...)
	sbuild := &AnimeMetaSelect{AnimeMetaQuery: amq}
	sbuild.label = animemeta.Label
	sbuild.flds, sbuild.scan = &amq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AnimeMetaSelect configured with the given aggregations.
func (amq *AnimeMetaQuery) Aggregate(fns ...AggregateFunc) *AnimeMetaSelect {
	return amq.Select().Aggregate(fns...)
}

func (amq *AnimeMetaQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range amq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, amq); err != nil {
				return err
			}
		}
	}
	for _, f := range amq.ctx.Fields {
		if !animemeta.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if amq.path != nil {
		prev, err := amq.path(ctx)
		if err != nil {
			return err
		}
		amq.sql = prev
	}
	return nil
}

func (amq *AnimeMetaQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*AnimeMeta, error) {
	var (
		nodes = []*AnimeMeta{}
		_spec = amq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*AnimeMeta).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &AnimeMeta{config: amq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, amq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (amq *AnimeMetaQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := amq.querySpec()
	_spec.Node.Columns = amq.ctx.Fields
	if len(amq.ctx.Fields) > 0 {
		_spec.Unique = amq.ctx.Unique != nil && *amq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, amq.driver, _spec)
}

func (amq *AnimeMetaQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(animemeta.Table, animemeta.Columns, sqlgraph.NewFieldSpec(animemeta.FieldID, field.TypeInt))
	_spec.From = amq.sql
	if unique := amq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if amq.path != nil {
		_spec.Unique = true
	}
	if fields := amq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, animemeta.FieldID)
		for i := range fields {
			if fields[i] != animemeta.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := amq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := amq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := amq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := amq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (amq *AnimeMetaQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(amq.driver.Dialect())
	t1 := builder.Table(animemeta.Table)
	columns := amq.ctx.Fields
	if len(columns) == 0 {
		columns = animemeta.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if amq.sql != nil {
		selector = amq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if amq.ctx.Unique != nil && *amq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range amq.predicates {
		p(selector)
	}
	for _, p := range amq.order {
		p(selector)
	}
	if offset := amq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := amq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AnimeMetaGroupBy is the group-by builder for AnimeMeta entities.
type AnimeMetaGroupBy struct {
	selector
	build *AnimeMetaQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (amgb *AnimeMetaGroupBy) Aggregate(fns ...AggregateFunc) *AnimeMetaGroupBy {
	amgb.fns = append(amgb.fns, fns...)
	return amgb
}

// Scan applies the selector query and scans the result into the given value.
func (amgb *AnimeMetaGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, amgb.build.ctx, "GroupBy")
	if err := amgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AnimeMetaQuery, *AnimeMetaGroupBy](ctx, amgb.build, amgb, amgb.build.inters, v)
}

func (amgb *AnimeMetaGroupBy) sqlScan(ctx context.Context, root *AnimeMetaQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(amgb.fns))
	for _, fn := range amgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*amgb.flds)+len(amgb.fns))
		for _, f := range *amgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*amgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := amgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AnimeMetaSelect is the builder for selecting fields of AnimeMeta entities.
type AnimeMetaSelect struct {
	*AnimeMetaQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ams *AnimeMetaSelect) Aggregate(fns ...AggregateFunc) *AnimeMetaSelect {
	ams.fns = append(ams.fns, fns...)
	return ams
}

// Scan applies the selector query and scans the result into the given value.
func (ams *AnimeMetaSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ams.ctx, "Select")
	if err := ams.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AnimeMetaQuery, *AnimeMetaSelect](ctx, ams.AnimeMetaQuery, ams, ams.inters, v)
}

func (ams *AnimeMetaSelect) sqlScan(ctx context.Context, root *AnimeMetaQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ams.fns))
	for _, fn := range ams.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ams.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ams.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
