// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"mikanani-v2/internal/data/ent/migrate"

	"mikanani-v2/internal/data/ent/animemeta"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// AnimeMeta is the client for interacting with the AnimeMeta builders.
	AnimeMeta *AnimeMetaClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.AnimeMeta = NewAnimeMetaClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		AnimeMeta: NewAnimeMetaClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:       ctx,
		config:    cfg,
		AnimeMeta: NewAnimeMetaClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		AnimeMeta.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.AnimeMeta.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.AnimeMeta.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *AnimeMetaMutation:
		return c.AnimeMeta.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// AnimeMetaClient is a client for the AnimeMeta schema.
type AnimeMetaClient struct {
	config
}

// NewAnimeMetaClient returns a client for the AnimeMeta from the given config.
func NewAnimeMetaClient(c config) *AnimeMetaClient {
	return &AnimeMetaClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `animemeta.Hooks(f(g(h())))`.
func (c *AnimeMetaClient) Use(hooks ...Hook) {
	c.hooks.AnimeMeta = append(c.hooks.AnimeMeta, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `animemeta.Intercept(f(g(h())))`.
func (c *AnimeMetaClient) Intercept(interceptors ...Interceptor) {
	c.inters.AnimeMeta = append(c.inters.AnimeMeta, interceptors...)
}

// Create returns a builder for creating a AnimeMeta entity.
func (c *AnimeMetaClient) Create() *AnimeMetaCreate {
	mutation := newAnimeMetaMutation(c.config, OpCreate)
	return &AnimeMetaCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of AnimeMeta entities.
func (c *AnimeMetaClient) CreateBulk(builders ...*AnimeMetaCreate) *AnimeMetaCreateBulk {
	return &AnimeMetaCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *AnimeMetaClient) MapCreateBulk(slice any, setFunc func(*AnimeMetaCreate, int)) *AnimeMetaCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &AnimeMetaCreateBulk{err: fmt.Errorf("calling to AnimeMetaClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*AnimeMetaCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &AnimeMetaCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for AnimeMeta.
func (c *AnimeMetaClient) Update() *AnimeMetaUpdate {
	mutation := newAnimeMetaMutation(c.config, OpUpdate)
	return &AnimeMetaUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *AnimeMetaClient) UpdateOne(am *AnimeMeta) *AnimeMetaUpdateOne {
	mutation := newAnimeMetaMutation(c.config, OpUpdateOne, withAnimeMeta(am))
	return &AnimeMetaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *AnimeMetaClient) UpdateOneID(id int) *AnimeMetaUpdateOne {
	mutation := newAnimeMetaMutation(c.config, OpUpdateOne, withAnimeMetaID(id))
	return &AnimeMetaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for AnimeMeta.
func (c *AnimeMetaClient) Delete() *AnimeMetaDelete {
	mutation := newAnimeMetaMutation(c.config, OpDelete)
	return &AnimeMetaDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *AnimeMetaClient) DeleteOne(am *AnimeMeta) *AnimeMetaDeleteOne {
	return c.DeleteOneID(am.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *AnimeMetaClient) DeleteOneID(id int) *AnimeMetaDeleteOne {
	builder := c.Delete().Where(animemeta.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &AnimeMetaDeleteOne{builder}
}

// Query returns a query builder for AnimeMeta.
func (c *AnimeMetaClient) Query() *AnimeMetaQuery {
	return &AnimeMetaQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeAnimeMeta},
		inters: c.Interceptors(),
	}
}

// Get returns a AnimeMeta entity by its id.
func (c *AnimeMetaClient) Get(ctx context.Context, id int) (*AnimeMeta, error) {
	return c.Query().Where(animemeta.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *AnimeMetaClient) GetX(ctx context.Context, id int) *AnimeMeta {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *AnimeMetaClient) Hooks() []Hook {
	return c.hooks.AnimeMeta
}

// Interceptors returns the client interceptors.
func (c *AnimeMetaClient) Interceptors() []Interceptor {
	return c.inters.AnimeMeta
}

func (c *AnimeMetaClient) mutate(ctx context.Context, m *AnimeMetaMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&AnimeMetaCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&AnimeMetaUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&AnimeMetaUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&AnimeMetaDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown AnimeMeta mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		AnimeMeta []ent.Hook
	}
	inters struct {
		AnimeMeta []ent.Interceptor
	}
)
