// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"mikanani-v2/internal/biz"
	"mikanani-v2/internal/conf"
	"mikanani-v2/internal/data"
	"mikanani-v2/internal/server"
	"mikanani-v2/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, utils *conf.Utils, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	animeMetaRepo := data.NewAnimeMetaRepo(dataData, logger)
	animeDocRepo := data.NewAnimeDocRepo(dataData, confData, logger)
	animeUsecase := biz.NewAnimeUsecase(animeMetaRepo, animeDocRepo, logger)
	mikananiServiceService := service.NewMikananiServiceService(utils, animeUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, mikananiServiceService, logger)
	httpServer := server.NewHTTPServer(confServer, mikananiServiceService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
