// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"news-subscriber-bff/internal/data/ent/articlemeta"
	"news-subscriber-bff/internal/data/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ArticleMetaUpdate is the builder for updating ArticleMeta entities.
type ArticleMetaUpdate struct {
	config
	hooks    []Hook
	mutation *ArticleMetaMutation
}

// Where appends a list predicates to the ArticleMetaUpdate builder.
func (amu *ArticleMetaUpdate) Where(ps ...predicate.ArticleMeta) *ArticleMetaUpdate {
	amu.mutation.Where(ps...)
	return amu
}

// SetUID sets the "uid" field.
func (amu *ArticleMetaUpdate) SetUID(i int64) *ArticleMetaUpdate {
	amu.mutation.ResetUID()
	amu.mutation.SetUID(i)
	return amu
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (amu *ArticleMetaUpdate) SetNillableUID(i *int64) *ArticleMetaUpdate {
	if i != nil {
		amu.SetUID(*i)
	}
	return amu
}

// AddUID adds i to the "uid" field.
func (amu *ArticleMetaUpdate) AddUID(i int64) *ArticleMetaUpdate {
	amu.mutation.AddUID(i)
	return amu
}

// SetTitle sets the "title" field.
func (amu *ArticleMetaUpdate) SetTitle(s string) *ArticleMetaUpdate {
	amu.mutation.SetTitle(s)
	return amu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (amu *ArticleMetaUpdate) SetNillableTitle(s *string) *ArticleMetaUpdate {
	if s != nil {
		amu.SetTitle(*s)
	}
	return amu
}

// SetTags sets the "tags" field.
func (amu *ArticleMetaUpdate) SetTags(s []string) *ArticleMetaUpdate {
	amu.mutation.SetTags(s)
	return amu
}

// AppendTags appends s to the "tags" field.
func (amu *ArticleMetaUpdate) AppendTags(s []string) *ArticleMetaUpdate {
	amu.mutation.AppendTags(s)
	return amu
}

// SetCreateTime sets the "createTime" field.
func (amu *ArticleMetaUpdate) SetCreateTime(t time.Time) *ArticleMetaUpdate {
	amu.mutation.SetCreateTime(t)
	return amu
}

// SetNillableCreateTime sets the "createTime" field if the given value is not nil.
func (amu *ArticleMetaUpdate) SetNillableCreateTime(t *time.Time) *ArticleMetaUpdate {
	if t != nil {
		amu.SetCreateTime(*t)
	}
	return amu
}

// SetUpdateTime sets the "updateTime" field.
func (amu *ArticleMetaUpdate) SetUpdateTime(t time.Time) *ArticleMetaUpdate {
	amu.mutation.SetUpdateTime(t)
	return amu
}

// SetNillableUpdateTime sets the "updateTime" field if the given value is not nil.
func (amu *ArticleMetaUpdate) SetNillableUpdateTime(t *time.Time) *ArticleMetaUpdate {
	if t != nil {
		amu.SetUpdateTime(*t)
	}
	return amu
}

// Mutation returns the ArticleMetaMutation object of the builder.
func (amu *ArticleMetaUpdate) Mutation() *ArticleMetaMutation {
	return amu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (amu *ArticleMetaUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, amu.sqlSave, amu.mutation, amu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (amu *ArticleMetaUpdate) SaveX(ctx context.Context) int {
	affected, err := amu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (amu *ArticleMetaUpdate) Exec(ctx context.Context) error {
	_, err := amu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (amu *ArticleMetaUpdate) ExecX(ctx context.Context) {
	if err := amu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (amu *ArticleMetaUpdate) check() error {
	if v, ok := amu.mutation.Title(); ok {
		if err := articlemeta.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ArticleMeta.title": %w`, err)}
		}
	}
	return nil
}

func (amu *ArticleMetaUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := amu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(articlemeta.Table, articlemeta.Columns, sqlgraph.NewFieldSpec(articlemeta.FieldID, field.TypeInt))
	if ps := amu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := amu.mutation.UID(); ok {
		_spec.SetField(articlemeta.FieldUID, field.TypeInt64, value)
	}
	if value, ok := amu.mutation.AddedUID(); ok {
		_spec.AddField(articlemeta.FieldUID, field.TypeInt64, value)
	}
	if value, ok := amu.mutation.Title(); ok {
		_spec.SetField(articlemeta.FieldTitle, field.TypeString, value)
	}
	if value, ok := amu.mutation.Tags(); ok {
		_spec.SetField(articlemeta.FieldTags, field.TypeJSON, value)
	}
	if value, ok := amu.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, articlemeta.FieldTags, value)
		})
	}
	if value, ok := amu.mutation.CreateTime(); ok {
		_spec.SetField(articlemeta.FieldCreateTime, field.TypeTime, value)
	}
	if value, ok := amu.mutation.UpdateTime(); ok {
		_spec.SetField(articlemeta.FieldUpdateTime, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, amu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{articlemeta.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	amu.mutation.done = true
	return n, nil
}

// ArticleMetaUpdateOne is the builder for updating a single ArticleMeta entity.
type ArticleMetaUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArticleMetaMutation
}

// SetUID sets the "uid" field.
func (amuo *ArticleMetaUpdateOne) SetUID(i int64) *ArticleMetaUpdateOne {
	amuo.mutation.ResetUID()
	amuo.mutation.SetUID(i)
	return amuo
}

// SetNillableUID sets the "uid" field if the given value is not nil.
func (amuo *ArticleMetaUpdateOne) SetNillableUID(i *int64) *ArticleMetaUpdateOne {
	if i != nil {
		amuo.SetUID(*i)
	}
	return amuo
}

// AddUID adds i to the "uid" field.
func (amuo *ArticleMetaUpdateOne) AddUID(i int64) *ArticleMetaUpdateOne {
	amuo.mutation.AddUID(i)
	return amuo
}

// SetTitle sets the "title" field.
func (amuo *ArticleMetaUpdateOne) SetTitle(s string) *ArticleMetaUpdateOne {
	amuo.mutation.SetTitle(s)
	return amuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (amuo *ArticleMetaUpdateOne) SetNillableTitle(s *string) *ArticleMetaUpdateOne {
	if s != nil {
		amuo.SetTitle(*s)
	}
	return amuo
}

// SetTags sets the "tags" field.
func (amuo *ArticleMetaUpdateOne) SetTags(s []string) *ArticleMetaUpdateOne {
	amuo.mutation.SetTags(s)
	return amuo
}

// AppendTags appends s to the "tags" field.
func (amuo *ArticleMetaUpdateOne) AppendTags(s []string) *ArticleMetaUpdateOne {
	amuo.mutation.AppendTags(s)
	return amuo
}

// SetCreateTime sets the "createTime" field.
func (amuo *ArticleMetaUpdateOne) SetCreateTime(t time.Time) *ArticleMetaUpdateOne {
	amuo.mutation.SetCreateTime(t)
	return amuo
}

// SetNillableCreateTime sets the "createTime" field if the given value is not nil.
func (amuo *ArticleMetaUpdateOne) SetNillableCreateTime(t *time.Time) *ArticleMetaUpdateOne {
	if t != nil {
		amuo.SetCreateTime(*t)
	}
	return amuo
}

// SetUpdateTime sets the "updateTime" field.
func (amuo *ArticleMetaUpdateOne) SetUpdateTime(t time.Time) *ArticleMetaUpdateOne {
	amuo.mutation.SetUpdateTime(t)
	return amuo
}

// SetNillableUpdateTime sets the "updateTime" field if the given value is not nil.
func (amuo *ArticleMetaUpdateOne) SetNillableUpdateTime(t *time.Time) *ArticleMetaUpdateOne {
	if t != nil {
		amuo.SetUpdateTime(*t)
	}
	return amuo
}

// Mutation returns the ArticleMetaMutation object of the builder.
func (amuo *ArticleMetaUpdateOne) Mutation() *ArticleMetaMutation {
	return amuo.mutation
}

// Where appends a list predicates to the ArticleMetaUpdate builder.
func (amuo *ArticleMetaUpdateOne) Where(ps ...predicate.ArticleMeta) *ArticleMetaUpdateOne {
	amuo.mutation.Where(ps...)
	return amuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (amuo *ArticleMetaUpdateOne) Select(field string, fields ...string) *ArticleMetaUpdateOne {
	amuo.fields = append([]string{field}, fields...)
	return amuo
}

// Save executes the query and returns the updated ArticleMeta entity.
func (amuo *ArticleMetaUpdateOne) Save(ctx context.Context) (*ArticleMeta, error) {
	return withHooks(ctx, amuo.sqlSave, amuo.mutation, amuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (amuo *ArticleMetaUpdateOne) SaveX(ctx context.Context) *ArticleMeta {
	node, err := amuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (amuo *ArticleMetaUpdateOne) Exec(ctx context.Context) error {
	_, err := amuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (amuo *ArticleMetaUpdateOne) ExecX(ctx context.Context) {
	if err := amuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (amuo *ArticleMetaUpdateOne) check() error {
	if v, ok := amuo.mutation.Title(); ok {
		if err := articlemeta.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "ArticleMeta.title": %w`, err)}
		}
	}
	return nil
}

func (amuo *ArticleMetaUpdateOne) sqlSave(ctx context.Context) (_node *ArticleMeta, err error) {
	if err := amuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(articlemeta.Table, articlemeta.Columns, sqlgraph.NewFieldSpec(articlemeta.FieldID, field.TypeInt))
	id, ok := amuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ArticleMeta.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := amuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, articlemeta.FieldID)
		for _, f := range fields {
			if !articlemeta.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != articlemeta.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := amuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := amuo.mutation.UID(); ok {
		_spec.SetField(articlemeta.FieldUID, field.TypeInt64, value)
	}
	if value, ok := amuo.mutation.AddedUID(); ok {
		_spec.AddField(articlemeta.FieldUID, field.TypeInt64, value)
	}
	if value, ok := amuo.mutation.Title(); ok {
		_spec.SetField(articlemeta.FieldTitle, field.TypeString, value)
	}
	if value, ok := amuo.mutation.Tags(); ok {
		_spec.SetField(articlemeta.FieldTags, field.TypeJSON, value)
	}
	if value, ok := amuo.mutation.AppendedTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, articlemeta.FieldTags, value)
		})
	}
	if value, ok := amuo.mutation.CreateTime(); ok {
		_spec.SetField(articlemeta.FieldCreateTime, field.TypeTime, value)
	}
	if value, ok := amuo.mutation.UpdateTime(); ok {
		_spec.SetField(articlemeta.FieldUpdateTime, field.TypeTime, value)
	}
	_node = &ArticleMeta{config: amuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, amuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{articlemeta.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	amuo.mutation.done = true
	return _node, nil
}
