// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"news-subscriber-bff/internal/data/ent/articlemeta"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ArticleMeta is the model entity for the ArticleMeta schema.
type ArticleMeta struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// UID holds the value of the "uid" field.
	UID int64 `json:"uid,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags []string `json:"tags,omitempty"`
	// CreateTime holds the value of the "createTime" field.
	CreateTime time.Time `json:"createTime,omitempty"`
	// UpdateTime holds the value of the "updateTime" field.
	UpdateTime   time.Time `json:"updateTime,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ArticleMeta) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case articlemeta.FieldTags:
			values[i] = new([]byte)
		case articlemeta.FieldID, articlemeta.FieldUID:
			values[i] = new(sql.NullInt64)
		case articlemeta.FieldTitle:
			values[i] = new(sql.NullString)
		case articlemeta.FieldCreateTime, articlemeta.FieldUpdateTime:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ArticleMeta fields.
func (am *ArticleMeta) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case articlemeta.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			am.ID = int(value.Int64)
		case articlemeta.FieldUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				am.UID = value.Int64
			}
		case articlemeta.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				am.Title = value.String
			}
		case articlemeta.FieldTags:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &am.Tags); err != nil {
					return fmt.Errorf("unmarshal field tags: %w", err)
				}
			}
		case articlemeta.FieldCreateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createTime", values[i])
			} else if value.Valid {
				am.CreateTime = value.Time
			}
		case articlemeta.FieldUpdateTime:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updateTime", values[i])
			} else if value.Valid {
				am.UpdateTime = value.Time
			}
		default:
			am.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ArticleMeta.
// This includes values selected through modifiers, order, etc.
func (am *ArticleMeta) Value(name string) (ent.Value, error) {
	return am.selectValues.Get(name)
}

// Update returns a builder for updating this ArticleMeta.
// Note that you need to call ArticleMeta.Unwrap() before calling this method if this ArticleMeta
// was returned from a transaction, and the transaction was committed or rolled back.
func (am *ArticleMeta) Update() *ArticleMetaUpdateOne {
	return NewArticleMetaClient(am.config).UpdateOne(am)
}

// Unwrap unwraps the ArticleMeta entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (am *ArticleMeta) Unwrap() *ArticleMeta {
	_tx, ok := am.config.driver.(*txDriver)
	if !ok {
		panic("ent: ArticleMeta is not a transactional entity")
	}
	am.config.driver = _tx.drv
	return am
}

// String implements the fmt.Stringer.
func (am *ArticleMeta) String() string {
	var builder strings.Builder
	builder.WriteString("ArticleMeta(")
	builder.WriteString(fmt.Sprintf("id=%v, ", am.ID))
	builder.WriteString("uid=")
	builder.WriteString(fmt.Sprintf("%v", am.UID))
	builder.WriteString(", ")
	builder.WriteString("title=")
	builder.WriteString(am.Title)
	builder.WriteString(", ")
	builder.WriteString("tags=")
	builder.WriteString(fmt.Sprintf("%v", am.Tags))
	builder.WriteString(", ")
	builder.WriteString("createTime=")
	builder.WriteString(am.CreateTime.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updateTime=")
	builder.WriteString(am.UpdateTime.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ArticleMetaSlice is a parsable slice of ArticleMeta.
type ArticleMetaSlice []*ArticleMeta
