// Code generated by ent, DO NOT EDIT.

package ent

import (
	"news-subscriber-bff/internal/data/ent/articlemeta"
	"news-subscriber-bff/internal/data/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	articlemetaFields := schema.ArticleMeta{}.Fields()
	_ = articlemetaFields
	// articlemetaDescTitle is the schema descriptor for title field.
	articlemetaDescTitle := articlemetaFields[1].Descriptor()
	// articlemeta.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	articlemeta.TitleValidator = articlemetaDescTitle.Validators[0].(func(string) error)
	// articlemetaDescCreateTime is the schema descriptor for createTime field.
	articlemetaDescCreateTime := articlemetaFields[3].Descriptor()
	// articlemeta.DefaultCreateTime holds the default value on creation for the createTime field.
	articlemeta.DefaultCreateTime = articlemetaDescCreateTime.Default.(func() time.Time)
	// articlemetaDescUpdateTime is the schema descriptor for updateTime field.
	articlemetaDescUpdateTime := articlemetaFields[4].Descriptor()
	// articlemeta.DefaultUpdateTime holds the default value on creation for the updateTime field.
	articlemeta.DefaultUpdateTime = articlemetaDescUpdateTime.Default.(func() time.Time)
}
