apiVersion: batch/v1
kind: CronJob
metadata:
  name: mikanani-dispatcher
  namespace: web-general
spec:
  schedule: "0 */4 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: mikanani-dispatcher
            image: kapibara.harbor.com/<DOCKER_HUB_REPO>/<MikananiImage>
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: mikanani-config
            command: ["mikanani"]
            args: ["--mode", "sqs-dispatch"]
            resources:
              limits:
                memory: "128Mi"
                cpu: "50m"
