apiVersion: v1
kind: Service
metadata:
  name: mikanani-svc
  namespace: web-general
spec:
  selector:
    app: mikanani-worker
  ports:
    - protocol: TCP
      nodePort: 30007
      port: 50051      
      targetPort: 50051
  type: NodePort
