apiVersion: v1
kind: Service
metadata:
  name: mikanani-svc
  namespace: web-general
spec:
  selector:
    app: mikanani-worker
  ports:
    - protocol: TCP
      name: grpcPort
      port: 15051       
      targetPort: 50051
  type: NodePort
