apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikanani-worker
  namespace: web-general
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikanani-worker
      feature: worker
  template:
    metadata:
      labels:
        app: mikanani-worker
        feature: worker
    spec:
      containers:
      - name: mikanani-worker
        image: <DOCKER_HUB_REPO>/<MikananiImage>
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: mikanani-config
        command: ["mikanani"]
        args: ["--mode", "sqs-worker"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
