apiVersion: apps/v1
kind: Deployment
metadata:
  name: mikanani-worker
  namespace: web-general
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mikanani-worker
      feature: worker
  template:
    metadata:
      labels:
        app: mikanani-worker
        feature: worker
    spec:
      containers:
      - name: mikanani-worker
        image: <DOCKER_HUB_REPO>/<MikananiImage>
        imagePullPolicy: Never
        env:
        - name: HTTP_PROXY
          value: "http://<node-ip>:<proxy-port>"
        - name: HTTPS_PROXY
          value: "http://<node-ip>:<proxy-port>"
        - name: NO_PROXY
          value: "localhost,127.0.0.1"
        envFrom:
        - secretRef:
            name: mikanani-config
        command: ["python"]
        args: ["main.py", "mikanani", "--mode", "sqs-worker"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
