// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AnimeMetaColumns holds the columns for the "anime_meta" table.
	AnimeMetaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "uid", Type: field.TypeInt64, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "download_bitmap", Type: field.TypeInt64, Default: 0},
		{Name: "is_active", Type: field.TypeBool, Default: false},
		{Name: "tags", Type: field.TypeJSON, Nullable: true},
		{Name: "episodes", Type: field.TypeInt64, Default: 24},
		{Name: "create_time", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
		{Name: "update_time", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// AnimeMetaTable holds the schema information for the "anime_meta" table.
	AnimeMetaTable = &schema.Table{
		Name:       "anime_meta",
		Columns:    AnimeMetaColumns,
		PrimaryKey: []*schema.Column{AnimeMetaColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AnimeMetaTable,
	}
)

func init() {
}
