name: Mikanani Deployment
run-name: Deploy ${{ github.event.inputs.module }}-${{ github.event.inputs.submodule }}

on:
  workflow_dispatch:
    inputs:
      module:
        type: choice
        description: module
        options:
          - Mikanani-sqs
        required: true
      submodule:
        type: choice
        description: worker/dispatcher/all
        options:
          - worker
          - dispatcher
          - sync
          - all
        required: true
jobs:

  build-docker-image-and-deploy-to-k8s:
    runs-on: self-hosted

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Build Docker image
      run: |
        image_name=`echo ${{ github.event.inputs.module }} | awk '{print tolower($1)}'`
        docker build -f ./deployments/docker/mikanani/Dockerfile -t ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}/$image_name:latest .
        export KUBECONFIG=$HOME/.kube/config
        docker save ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}/$image_name:latest | k3s ctr images import -
        docker rmi ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}/$image_name:latest
      
    - name: Deploy on Kubernetes
      run: |
        image_name=`echo ${{ github.event.inputs.module }} | awk '{print tolower($1)}'`
        image="${image_name}:latest"
        repo="${{ secrets.DOCKER_HUB_USERNAME }}\/${{ secrets.DOCKER_HUB_REPO }}"
        nfsip="${{ secrets.NFS_SERVER_IP }}"
        mikananinfspath="${{ secrets.MIKANANI_NFS_PATH }}"

        sed -i "s|<DOCKER_HUB_REPO>|${repo}|g" ./deployments/kubernetes/mikanani/worker.yaml
        sed -i "s|<MikananiImage>|${image}|g" ./deployments/kubernetes/mikanani/worker.yaml

        sed -i "s|<DOCKER_HUB_REPO>|${repo}|g" ./deployments/kubernetes/mikanani/dispatcher.yaml
        sed -i "s|<MikananiImage>|${image}|g" ./deployments/kubernetes/mikanani/dispatcher.yaml

        sed -i "s|<DOCKER_HUB_REPO>|${repo}|g" ./deployments/kubernetes/mikanani/sync.yaml
        sed -i "s|<MikananiImage>|${image}|g" ./deployments/kubernetes/mikanani/sync.yaml

        sed -i "s|<NFS_SERVER_IP>|${nfsip}|g" ./deployments/kubernetes/mikanani/sync.yaml
        sed -i "s|<MIKANANI_NFS_PATH>|${mikananinfspath}|g" ./deployments/kubernetes/mikanani/sync.yaml

        case "${{ github.event.inputs.submodule }}" in
        "worker")
        echo "Deploy worker only..."
        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/mikanani/worker.yaml
        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/mikanani/service.yaml
        ;;
        "dispatcher")
        echo "Deploy dispatcher only..."
        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/mikanani/dispatcher.yaml
        ;;
        "sync")
        echo "Deploy sync only..."
        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/mikanani/sync.yaml
        ;;
        "all")
        echo "Deploy all..."
        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/mikanani/worker.yaml
        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/mikanani/service.yaml
        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/mikanani/dispatcher.yaml
        echo ${{ secrets.M14_SUDO_PWD }} | sudo -S kubectl apply -f ./deployments/kubernetes/mikanani/sync.yaml
        ;;
        esac
