// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"news-subscriber-bff/internal/biz"
	"news-subscriber-bff/internal/conf"
	"news-subscriber-bff/internal/data"
	"news-subscriber-bff/internal/server"
	"news-subscriber-bff/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, utils *conf.Utils, logger log.Logger) (*kratos.App, func(), error) {
	dataData, cleanup, err := data.NewData(confData, logger)
	if err != nil {
		return nil, nil, err
	}
	articleRepo := data.NewArticleRepo(dataData, logger)
	articleUsecase := biz.NewArticleUsecase(articleRepo)
	articleService := service.NewArticleService(utils, articleUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, articleService, logger)
	httpServer := server.NewHTTPServer(confServer, articleService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
